server:
  port: 8080

spring:
  datasource:
    username: root
    password: root9876
    url: jdbc:mysql://39.105.166.160/springboot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity.*